<?php

namespace Aevitas\ConfigBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConfigController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/prod/jms_diextra/proxies/Aevitas-ConfigBundle-Controller-ConfigController.php';
        $n = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\ConfigBundle\\Controller\\ConfigController' => array('setEnvironmentAction' => array(0 => 'security.access.method_interceptor'), 'setMailerConfigAction' => array(0 => 'security.access.method_interceptor'), 'setLoyaltyConfigAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_8fbb75f8a507fc7c8649f039ca4d08ed736946dc\__CG__\Aevitas\ConfigBundle\Controller\ConfigController();
        $instance->__CGInterception__setLoader($n);
        return $instance;
    }
}
