<?php

namespace Aevitas\CustomerCodeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/prod/jms_diextra/proxies/Aevitas-CustomerCodeBundle-Controller-DefaultController.php';
        $p = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\CustomerCodeBundle\\Controller\\DefaultController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'downloadAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_82148b2eb643ff1fa2bf8220c11fa37e32dfb33e\__CG__\Aevitas\CustomerCodeBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($p);
        return $instance;
    }
}
