<?php

namespace Vietland\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SecurityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Vietland\UserBundle\Controller\SecurityController();
        return $instance;
    }
}
