<?php

namespace Vietland\AevitasBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AevitasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Vietland\AevitasBundle\Controller\AevitasController();
        return $instance;
    }
}
