<?php

namespace Vietland\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/prod/jms_diextra/proxies/Vietland-UserBundle-Controller-GroupController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Vietland\\UserBundle\\Controller\\GroupController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'infoAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_b2f6873d3583053739e45eb9c9646ba3f2bc9a7e\__CG__\Vietland\UserBundle\Controller\GroupController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
