<?php

namespace MongoDBODMProxies\__CG__\Aevitas\CustomerCodeBundle\Document;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class CustomerCode extends \Aevitas\CustomerCodeBundle\Document\CustomerCode implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    public $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\DocumentNotFoundException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->__identifier__;
        }
        $this->__load();
        return parent::getId();
    }

    public function setPrefix($prefix)
    {
        $this->__load();
        return parent::setPrefix($prefix);
    }

    public function getPrefix()
    {
        $this->__load();
        return parent::getPrefix();
    }

    public function setStart($start)
    {
        $this->__load();
        return parent::setStart($start);
    }

    public function getStart()
    {
        $this->__load();
        return parent::getStart();
    }

    public function setEnd($end)
    {
        $this->__load();
        return parent::setEnd($end);
    }

    public function getEnd()
    {
        $this->__load();
        return parent::getEnd();
    }

    public function setStore(\Aevitas\LevisBundle\Document\Store $store)
    {
        $this->__load();
        return parent::setStore($store);
    }

    public function getStore()
    {
        $this->__load();
        return parent::getStore();
    }

    public function checkStartEnd(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {
        $this->__load();
        return parent::checkStartEnd($context);
    }

    public function getTrans()
    {
        $this->__load();
        return parent::getTrans();
    }

    public function addTransfer(\Aevitas\CustomerCodeBundle\Document\Transfer $tran)
    {
        $this->__load();
        return parent::addTransfer($tran);
    }

    public function createNewTransfer()
    {
        $this->__load();
        return parent::createNewTransfer();
    }

    public function setUsedById($id)
    {
        $this->__load();
        return parent::setUsedById($id);
    }

    public function getUsed()
    {
        $this->__load();
        return parent::getUsed();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'prefix', 'start', 'end', 'used', 'store', 'trans');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__documentPersister__->getClassMetadata();
            $original = $this->__documentPersister__->load($this->__identifier__);
            if ($original === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
        
    }
}