<?php

namespace Aevitas\ChannelBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessRepository extends DocumentRepository {

    private $count;

}