<?php

namespace Aevitas\ChannelBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Aevitas\ChannelBundle\Document\TemplateRule;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRuleRepository extends DocumentRepository {

    private $count;

}