<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AevitasLevisBundleDocumentStoreHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['oldId'])) {
            $value = $data['oldId'];
            $return = (int) $value;
            $this->class->reflFields['oldId']->setValue($document, $return);
            $hydratedData['oldId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['address'])) {
            $value = $data['address'];
            $return = (string) $value;
            $this->class->reflFields['address']->setValue($document, $return);
            $hydratedData['address'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['address2'])) {
            $value = $data['address2'];
            $return = (string) $value;
            $this->class->reflFields['address2']->setValue($document, $return);
            $hydratedData['address2'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['address3'])) {
            $value = $data['address3'];
            $return = (string) $value;
            $this->class->reflFields['address3']->setValue($document, $return);
            $hydratedData['address3'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['city'])) {
            $value = $data['city'];
            $return = (int) $value;
            $this->class->reflFields['city']->setValue($document, $return);
            $hydratedData['city'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['district'])) {
            $value = $data['district'];
            $return = (int) $value;
            $this->class->reflFields['district']->setValue($document, $return);
            $hydratedData['district'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phone'])) {
            $value = $data['phone'];
            $return = (string) $value;
            $this->class->reflFields['phone']->setValue($document, $return);
            $hydratedData['phone'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email'])) {
            $value = $data['email'];
            $return = (string) $value;
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fax'])) {
            $value = $data['fax'];
            $return = (string) $value;
            $this->class->reflFields['fax']->setValue($document, $return);
            $hydratedData['fax'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['alias'])) {
            $value = $data['alias'];
            $return = (string) $value;
            $this->class->reflFields['alias']->setValue($document, $return);
            $hydratedData['alias'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['userId'])) {
            $value = $data['userId'];
            $return = (int) $value;
            $this->class->reflFields['userId']->setValue($document, $return);
            $hydratedData['userId'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['visible'])) {
            $value = $data['visible'];
            $return = (bool) $value;
            $this->class->reflFields['visible']->setValue($document, $return);
            $hydratedData['visible'] = $return;
        }
        return $hydratedData;
    }
}