<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AevitasLevisBundleDocumentEmailSmsTemplateHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['bodymail'])) {
            $value = $data['bodymail'];
            $return = (string) $value;
            $this->class->reflFields['bodymail']->setValue($document, $return);
            $hydratedData['bodymail'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['bodysms'])) {
            $value = $data['bodysms'];
            $return = (string) $value;
            $this->class->reflFields['bodysms']->setValue($document, $return);
            $hydratedData['bodysms'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['gender'])) {
            $value = $data['gender'];
            $return = (int) $value;
            $this->class->reflFields['gender']->setValue($document, $return);
            $hydratedData['gender'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['group'])) {
            $value = $data['group'];
            $return = (string) $value;
            $this->class->reflFields['group']->setValue($document, $return);
            $hydratedData['group'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['city'])) {
            $value = $data['city'];
            $return = (string) $value;
            $this->class->reflFields['city']->setValue($document, $return);
            $hydratedData['city'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['district'])) {
            $value = $data['district'];
            $return = (string) $value;
            $this->class->reflFields['district']->setValue($document, $return);
            $hydratedData['district'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['cityName'])) {
            $value = $data['cityName'];
            $return = (string) $value;
            $this->class->reflFields['cityName']->setValue($document, $return);
            $hydratedData['cityName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['districtName'])) {
            $value = $data['districtName'];
            $return = (string) $value;
            $this->class->reflFields['districtName']->setValue($document, $return);
            $hydratedData['districtName'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['level'])) {
            $value = $data['level'];
            $return = (int) $value;
            $this->class->reflFields['level']->setValue($document, $return);
            $hydratedData['level'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['type'])) {
            $value = $data['type'];
            $return = (string) $value;
            $this->class->reflFields['type']->setValue($document, $return);
            $hydratedData['type'] = $return;
        }
        return $hydratedData;
    }
}