<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AevitasLevisBundleDocumentAbstractRedeemHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['user'])) {
            $reference = $data['user'];
            if (isset($this->class->fieldMappings['user']['simple']) && $this->class->fieldMappings['user']['simple']) {
                $className = $this->class->fieldMappings['user']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['user'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['user']->setValue($document, $return);
            $hydratedData['user'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['uid'])) {
            $value = $data['uid'];
            $return = (int) $value;
            $this->class->reflFields['uid']->setValue($document, $return);
            $hydratedData['uid'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['store'])) {
            $reference = $data['store'];
            if (isset($this->class->fieldMappings['store']['simple']) && $this->class->fieldMappings['store']['simple']) {
                $className = $this->class->fieldMappings['store']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['store'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['store']->setValue($document, $return);
            $hydratedData['store'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created'])) {
            $value = $data['created'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } else { $return = new \DateTime($value); }
            $this->class->reflFields['created']->setValue($document, clone $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['sid'])) {
            $value = $data['sid'];
            $return = (int) $value;
            $this->class->reflFields['sid']->setValue($document, $return);
            $hydratedData['sid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['hash'])) {
            $value = $data['hash'];
            $return = (string) $value;
            $this->class->reflFields['hash']->setValue($document, $return);
            $hydratedData['hash'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['auth'])) {
            $value = $data['auth'];
            $return = (bool) $value;
            $this->class->reflFields['auth']->setValue($document, $return);
            $hydratedData['auth'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['point'])) {
            $value = $data['point'];
            $return = (int) $value;
            $this->class->reflFields['point']->setValue($document, $return);
            $hydratedData['point'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['bPoint'])) {
            $value = $data['bPoint'];
            $return = (float) $value;
            $this->class->reflFields['bPoint']->setValue($document, $return);
            $hydratedData['bPoint'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['aPoint'])) {
            $value = $data['aPoint'];
            $return = (float) $value;
            $this->class->reflFields['aPoint']->setValue($document, $return);
            $hydratedData['aPoint'] = $return;
        }
        return $hydratedData;
    }
}