<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AevitasCustomerCodeBundleDocumentCustomerCodeHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['prefix'])) {
            $value = $data['prefix'];
            $return = (int) $value;
            $this->class->reflFields['prefix']->setValue($document, $return);
            $hydratedData['prefix'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['start'])) {
            $value = $data['start'];
            $return = (int) $value;
            $this->class->reflFields['start']->setValue($document, $return);
            $hydratedData['start'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['end'])) {
            $value = $data['end'];
            $return = (int) $value;
            $this->class->reflFields['end']->setValue($document, $return);
            $hydratedData['end'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['used'])) {
            $value = $data['used'];
            $return = (int) $value;
            $this->class->reflFields['used']->setValue($document, $return);
            $hydratedData['used'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['store'])) {
            $reference = $data['store'];
            if (isset($this->class->fieldMappings['store']['simple']) && $this->class->fieldMappings['store']['simple']) {
                $className = $this->class->fieldMappings['store']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['store'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['store']->setValue($document, $return);
            $hydratedData['store'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['trans']) ? $data['trans'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['trans']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['trans']->setValue($document, $return);
        $hydratedData['trans'] = $return;
        return $hydratedData;
    }
}