<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AevitasLevisBundleDocumentGiftMetaHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int") */
        if (isset($data['gid'])) {
            $value = $data['gid'];
            $return = (int) $value;
            $this->class->reflFields['gid']->setValue($document, $return);
            $hydratedData['gid'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['count'])) {
            $value = $data['count'];
            $return = (int) $value;
            $this->class->reflFields['count']->setValue($document, $return);
            $hydratedData['count'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['ship'])) {
            $value = $data['ship'];
            $return = (int) $value;
            $this->class->reflFields['ship']->setValue($document, $return);
            $hydratedData['ship'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }
        return $hydratedData;
    }
}