<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class VietlandStoreBundleDocumentJobqueueHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="int_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (int) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['bill'])) {
            $value = $data['bill'];
            $return = (string) $value;
            $this->class->reflFields['bill']->setValue($document, $return);
            $hydratedData['bill'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['data'])) {
            $value = $data['data'];
            $return = (string) $value;
            $this->class->reflFields['data']->setValue($document, $return);
            $hydratedData['data'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['start'])) {
            $value = $data['start'];
            $return = (int) $value;
            $this->class->reflFields['start']->setValue($document, $return);
            $hydratedData['start'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (bool) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }
        return $hydratedData;
    }
}