<?php

namespace Aevitas\LevisBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftArticleRepository extends DocumentRepository {

    private $count;

    public function getGifts($cat, $page = 1, $limit = 9, $sort = 'id') {
        if (!(int) $page)
            $page = 1;
        if (!(int) $limit)
            $limit = 9;
        if (is_null($sort))
            $sort = 'id';
        if (!is_null($cat) && 'Reward' != $cat)
            return $this->createQueryBuilder()
                            ->field('cat')->equals($cat)
                            ->limit((int) $limit)
                            ->skip(((int) $page - 1) * (int) $limit)->sort($sort, 'desc')
                            ->getQuery()
                            ->execute();
        else
            return $this->createQueryBuilder()
                            ->limit((int) $limit)
                            ->skip(((int) $page - 1) * (int) $limit)->sort($sort, 'desc')
                            ->getQuery()
                            ->execute();
    }

    public function getGiftInCategory($topcat, $catid, $page, $limit, $sort = 'id') {
        if (!(int) $page)
            $page = 1;
        if (!(int) $limit)
            $limit = 9;
        if (is_null($sort))
            $sort = 'id';

        $qb = $this->createQueryBuilder()
                        ->field('catid')->equals((int) $catid)
                        ->field('cat')->equals($topcat);
        $countQuery = clone $qb;
        $this->count = $countQuery->count()->getQuery()->execute();
        $qb->limit((int) $limit)
                ->skip(((int) $page - 1) * (int) $limit)->sort($sort, 'desc');
        return $qb->getQuery()
                        ->execute();
    }

    public function getCount() {
        return $this->count;
    }

}