<?php

namespace MongoDBODMProxies\__CG__\Vietland\UserBundle\Document;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class UserLog extends \Vietland\UserBundle\Document\UserLog implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    public $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\DocumentNotFoundException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getSchema()
    {
        $this->__load();
        return parent::getSchema();
    }

    public function setSchema($schema)
    {
        $this->__load();
        return parent::setSchema($schema);
    }

    public function addSchema($data)
    {
        $this->__load();
        return parent::addSchema($data);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getPoint()
    {
        $this->__load();
        return parent::getPoint();
    }

    public function setPoint($point)
    {
        $this->__load();
        return parent::setPoint($point);
    }

    public function getRid()
    {
        $this->__load();
        return parent::getRid();
    }

    public function setRid($rid)
    {
        $this->__load();
        return parent::setRid($rid);
    }

    public function getTotalPayment()
    {
        $this->__load();
        return parent::getTotalPayment();
    }

    public function setTotalPayment($totalPayment)
    {
        $this->__load();
        return parent::setTotalPayment($totalPayment);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->__identifier__;
        }
        $this->__load();
        return parent::getId();
    }

    public function setUser(\Vietland\UserBundle\Document\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setAction($action)
    {
        $this->__load();
        return parent::setAction($action);
    }

    public function getAction()
    {
        $this->__load();
        return parent::getAction();
    }

    public function setSubject($subject)
    {
        $this->__load();
        return parent::setSubject($subject);
    }

    public function getSubject()
    {
        $this->__load();
        return parent::getSubject();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setMd5($md5)
    {
        $this->__load();
        return parent::setMd5($md5);
    }

    public function getMd5()
    {
        $this->__load();
        return parent::getMd5();
    }

    public function setUid($uid)
    {
        $this->__load();
        return parent::setUid($uid);
    }

    public function getUid()
    {
        $this->__load();
        return parent::getUid();
    }

    public function prePersist()
    {
        $this->__load();
        return parent::prePersist();
    }

    public function postUpdate()
    {
        $this->__load();
        return parent::postUpdate();
    }

    public function postLoad()
    {
        $this->__load();
        return parent::postLoad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'user', 'action', 'subject', 'created', 'md5', 'uid', 'schema', 'type', 'point', 'totalPayment', 'rid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__documentPersister__->getClassMetadata();
            $original = $this->__documentPersister__->load($this->__identifier__);
            if ($original === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
        
    }
}