<?php

namespace Vietland\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * POSUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POSUserRepository extends EntityRepository
{
}
