<?php

namespace Aevitas\LevisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CheckoutController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Aevitas\LevisBundle\Controller\CheckoutController();
        return $instance;
    }
}
