<?php

namespace Aevitas\LevisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StoreController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/Aevitas-LevisBundle-Controller-StoreController.php';
        $f = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\LevisBundle\\Controller\\StoreController' => array('storeCreateAction' => array(0 => 'security.access.method_interceptor'), 'StoreEditAction' => array(0 => 'security.access.method_interceptor'), 'storeListAction' => array(0 => 'security.access.method_interceptor'), 'addUserToStore' => array(0 => 'security.access.method_interceptor'), 'removeUserFromStoreAction' => array(0 => 'security.access.method_interceptor'), 'removeUserStoreAction' => array(0 => 'security.access.method_interceptor'), 'searchAction' => array(0 => 'security.access.method_interceptor'), 'addUserForStoreAction' => array(0 => 'security.access.method_interceptor'), 'Point2VndAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionInfoAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionProcessAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionAuthAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionPrintAction' => array(0 => 'security.access.method_interceptor'), 'RedeemptionDeleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_67668e8a8d86c1096239fd2af3397afeb3c3e24a\__CG__\Aevitas\LevisBundle\Controller\StoreController();
        $instance->__CGInterception__setLoader($f);
        return $instance;
    }
}
