<?php

namespace Aevitas\PointBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/Aevitas-PointBundle-Controller-DefaultController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\PointBundle\\Controller\\DefaultController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'addNewAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'testAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_dea4b62c384196f6a2c0b9c43e5710c2867f6f4a\__CG__\Aevitas\PointBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
