<?php

namespace EnhancedProxy_21a06583a09fc60640e6a49f1914748735e7f951\__CG__\Aevitas\LevisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GiftController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/EnhancedProxy_21a06583a09fc60640e6a49f1914748735e7f951-__CG__-Aevitas-LevisBundle-Controller-GiftController.php';
        $aa = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\LevisBundle\\Controller\\GiftController' => array('importGiftAction' => array(0 => 'security.access.method_interceptor'), 'giftListAction' => array(0 => 'security.access.method_interceptor'), 'giftCreateAction' => array(0 => 'security.access.method_interceptor'), 'giftAddWishListAction' => array(0 => 'security.access.method_interceptor'), 'giftAddCategories' => array(0 => 'security.access.method_interceptor'), 'gifEditAction' => array(0 => 'security.access.method_interceptor'), 'categoryEditAction' => array(0 => 'security.access.method_interceptor'), 'categoriesListAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_a8c757a2e66370fe476ed0a990145c73a1c1d8bf\__CG__\Aevitas\LevisBundle\Controller\GiftController();
        $instance->__CGInterception__setLoader($aa);
        return $instance;
    }
}
