<?php

namespace EnhancedProxy_8fbb75f8a507fc7c8649f039ca4d08ed736946dc\__CG__\Aevitas\ConfigBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConfigController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/EnhancedProxy_8fbb75f8a507fc7c8649f039ca4d08ed736946dc-__CG__-Aevitas-ConfigBundle-Controller-ConfigController.php';
        $da = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\ConfigBundle\\Controller\\ConfigController' => array('setMailerConfigAction' => array(0 => 'security.access.method_interceptor'), 'setLoyaltyConfigAction' => array(0 => 'security.access.method_interceptor'), 'setEnvironmentAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_07572227931e8b28e4a08c40948e930d15d07953\__CG__\Aevitas\ConfigBundle\Controller\ConfigController();
        $instance->__CGInterception__setLoader($da);
        return $instance;
    }
}
