<?php

namespace EnhancedProxy_a639e67f84959ed3733c7466068a307312a95ff1\__CG__\Vietland\ElfinderBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/EnhancedProxy_a639e67f84959ed3733c7466068a307312a95ff1-__CG__-Vietland-ElfinderBundle-Controller-DefaultController.php';
        $ea = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Vietland\\ElfinderBundle\\Controller\\DefaultController' => array('uploadGiftAction' => array(0 => 'security.access.method_interceptor'), 'uploadAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_2d1fa340631133bcd604a07ee0e2b2050a9d6a4c\__CG__\Vietland\ElfinderBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($ea);
        return $instance;
    }
}
