<?php

namespace EnhancedProxy_dea4b62c384196f6a2c0b9c43e5710c2867f6f4a\__CG__\Aevitas\PointBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/EnhancedProxy_dea4b62c384196f6a2c0b9c43e5710c2867f6f4a-__CG__-Aevitas-PointBundle-Controller-DefaultController.php';
        $t = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\PointBundle\\Controller\\DefaultController' => array('testAction' => array(0 => 'security.access.method_interceptor'), 'indexAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'addNewAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_e6f4aa6f0bbec705639af4a36aa2e18c72cc8108\__CG__\Aevitas\PointBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($t);
        return $instance;
    }
}
