<?php

namespace EnhancedProxy_345014e321e3c5eade5e936f9e0f5207c0409bc0\__CG__\Aevitas\LevisBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DashboardController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/EnhancedProxy_345014e321e3c5eade5e936f9e0f5207c0409bc0-__CG__-Aevitas-LevisBundle-Controller-DashboardController.php';
        $ba = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Aevitas\\LevisBundle\\Controller\\DashboardController' => array('userStatementAction' => array(0 => 'security.access.method_interceptor'), 'updateAvatarAction' => array(0 => 'security.access.method_interceptor'), 'shoppingHistoryAction' => array(0 => 'security.access.method_interceptor'), 'saveTripleDateAction' => array(0 => 'security.access.method_interceptor'), 'profileExtendedAction' => array(0 => 'security.access.method_interceptor'), 'profileActivityAction' => array(0 => 'security.access.method_interceptor'), 'profileAction' => array(0 => 'security.access.method_interceptor'), 'dashboardAction' => array(0 => 'security.access.method_interceptor'), 'cropAvatar' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_1ca321c3c166b529003bdf57ea81e272d778314c\__CG__\Aevitas\LevisBundle\Controller\DashboardController();
        $instance->__CGInterception__setLoader($ba);
        return $instance;
    }
}
