<?php

namespace Vietland\ElfinderBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/levis-crm/app/cache/dev/jms_diextra/proxies/Vietland-ElfinderBundle-Controller-DefaultController.php';
        $o = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Vietland\\ElfinderBundle\\Controller\\DefaultController' => array('uploadAction' => array(0 => 'security.access.method_interceptor'), 'uploadGiftAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_a639e67f84959ed3733c7466068a307312a95ff1\__CG__\Vietland\ElfinderBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($o);
        return $instance;
    }
}
